# Generated by Django 5.2.6 on 2025-10-19 13:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255, verbose_name='Tên tác giả')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Tiểu sử')),
            ],
            options={
                'verbose_name': 'Tác giả',
                'verbose_name_plural': 'Tác giả',
                'db_table': 'author',
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('unit_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá (VNĐ)')),
                ('publish_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Năm xuất bản')),
                ('publisher', models.CharField(max_length=255, verbose_name='Nhà xuất bản')),
                ('remaining_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng còn lại')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('edition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phiên bản')),
                ('language', models.CharField(default='Tiếng Việt', max_length=50, verbose_name='Ngôn ngữ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
                'db_table': 'book',
                'ordering': ['-publish_year', 'book_title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='Tên thể loại')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Thể loại',
                'verbose_name_plural': 'Thể loại',
                'db_table': 'category',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=100, verbose_name='Tên chức năng')),
                ('screen_name', models.CharField(max_length=100, verbose_name='Tên màn hình')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('url_pattern', models.CharField(blank=True, help_text='VD: /readers/, /books/, /borrow/', max_length=200, verbose_name='URL pattern')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Chức năng',
                'verbose_name_plural': 'Chức năng',
                'db_table': 'function',
                'ordering': ['function_name'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_age', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Độ tuổi thấp nhất')),
                ('min_age', models.PositiveSmallIntegerField(default=55, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Độ tuổi cao nhất')),
                ('card_validity_period', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thời hạn thẻ (tháng)')),
                ('book_return_period', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nhận sách xuất bản trong vòng (năm)')),
                ('max_borrowed_books', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số sách tối đa được mượn')),
                ('max_borrow_days', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số ngày mượn sách tối đa')),
                ('fine_rate', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá tiền phạt (VNĐ/ngày)')),
                ('enable_receipt_amount_validation', models.BooleanField(default=True, verbose_name='Kiểm tra số tiền thu không vượt quá nợ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tham số hệ thống',
                'verbose_name_plural': 'Tham số hệ thống',
                'db_table': 'parameter',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_name', models.CharField(max_length=255, verbose_name='Tên độc giả')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('card_creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày lập thẻ')),
                ('expiration_date', models.DateTimeField(verbose_name='Ngày hết hạn thẻ')),
                ('total_debt', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng nợ (VNĐ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Độc giả',
                'verbose_name_plural': 'Độc giả',
                'db_table': 'reader',
                'ordering': ['-card_creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ReaderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_type_name', models.CharField(max_length=100, unique=True, verbose_name='Tên loại độc giả')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Loại độc giả',
                'verbose_name_plural': 'Loại độc giả',
                'db_table': 'reader_type',
                'ordering': ['reader_type_name'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_group_name', models.CharField(max_length=100, unique=True, verbose_name='Tên nhóm người dùng')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Nhóm người dùng',
                'verbose_name_plural': 'Nhóm người dùng',
                'db_table': 'user_group',
                'ordering': ['user_group_name'],
            },
        ),
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.author', verbose_name='Tác giả')),
            ],
            options={
                'verbose_name': 'Chi tiết tác giả',
                'verbose_name_plural': 'Chi tiết tác giả',
                'db_table': 'author_detail',
            },
        ),
        migrations.CreateModel(
            name='BookImportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Tổng tiền nhập sách')),
                ('import_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập sách')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Người lập phiếu')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Phiếu nhập sách',
                'verbose_name_plural': 'Phiếu nhập sách',
                'db_table': 'book_import_receipt',
                'ordering': ['-import_date'],
                'indexes': [models.Index(fields=['-import_date'], name='book_import_import__a340f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_borrowed', models.BooleanField(default=False, verbose_name='Đang được mượn')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã vạch')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_items', to='LibraryApp.book', verbose_name='Sách')),
            ],
            options={
                'verbose_name': 'Cuốn sách',
                'verbose_name_plural': 'Các cuốn sách',
                'db_table': 'book_item',
                'ordering': ['book', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BookTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=500, verbose_name='Tên tựa sách')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='book_titles', through='LibraryApp.AuthorDetail', to='LibraryApp.author', verbose_name='Tác giả')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_titles', to='LibraryApp.category', verbose_name='Thể loại')),
            ],
            options={
                'verbose_name': 'Tựa sách',
                'verbose_name_plural': 'Tựa sách',
                'db_table': 'book_title',
                'ordering': ['book_title'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='book_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='LibraryApp.booktitle', verbose_name='Tựa sách'),
        ),
        migrations.AddField(
            model_name='authordetail',
            name='book_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.booktitle', verbose_name='Tựa sách'),
        ),
        migrations.CreateModel(
            name='LateReturnReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày lập báo cáo')),
                ('borrow_date', models.DateTimeField(verbose_name='Ngày mượn')),
                ('late_return_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số ngày trễ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='late_reports', to='LibraryApp.bookitem', verbose_name='Cuốn sách')),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='late_reports', to='LibraryApp.reader', verbose_name='Độc giả')),
            ],
            options={
                'verbose_name': 'Báo cáo trả trễ',
                'verbose_name_plural': 'Báo cáo trả trễ',
                'db_table': 'late_return_report',
                'ordering': ['-date', '-late_return_days'],
            },
        ),
        migrations.CreateModel(
            name='BorrowReturnReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày mượn')),
                ('due_date', models.DateTimeField(verbose_name='Ngày phải trả')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thực trả')),
                ('fine_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiền phạt trả trễ')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_receipts', to='LibraryApp.bookitem', verbose_name='Cuốn sách')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_receipts', to='LibraryApp.reader', verbose_name='Độc giả')),
            ],
            options={
                'verbose_name': 'Phiếu mượn/trả sách',
                'verbose_name_plural': 'Phiếu mượn/trả sách',
                'db_table': 'borrow_return_receipt',
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.AddField(
            model_name='reader',
            name='reader_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readers', to='LibraryApp.readertype', verbose_name='Loại độc giả'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền thu')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày lập phiếu')),
                ('payment_method', models.CharField(default='Tiền mặt', max_length=50, verbose_name='Phương thức thanh toán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='LibraryApp.reader', verbose_name='Độc giả')),
            ],
            options={
                'verbose_name': 'Phiếu thu',
                'verbose_name_plural': 'Phiếu thu',
                'db_table': 'receipt',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportDetailByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Tháng')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Năm')),
                ('total_borrow_count', models.IntegerField(default=0, verbose_name='Tổng số lượt mượn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Báo cáo mượn sách theo thể loại',
                'verbose_name_plural': 'Báo cáo mượn sách theo thể loại',
                'db_table': 'report_detail_by_category',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['month', 'year'], name='report_deta_month_374931_idx')],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BorrowReportDetailByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_count', models.IntegerField(default=0, verbose_name='Số lượt mượn')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tỉ lệ (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_reports', to='LibraryApp.booktitle', verbose_name='Tựa sách')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_details', to='LibraryApp.reportdetailbycategory', verbose_name='Báo cáo')),
            ],
            options={
                'verbose_name': 'Chi tiết báo cáo theo thể loại',
                'verbose_name_plural': 'Chi tiết báo cáo theo thể loại',
                'db_table': 'borrow_report_detail_by_category',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='Xem')),
                ('can_add', models.BooleanField(default=False, verbose_name='Thêm')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Sửa')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Xóa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='LibraryApp.function', verbose_name='Chức năng')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='LibraryApp.usergroup', verbose_name='Nhóm người dùng')),
            ],
            options={
                'verbose_name': 'Quyền',
                'verbose_name_plural': 'Quyền',
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('position', models.CharField(help_text='VD: Thủ thư trưởng, Thủ thư, Nhân viên...', max_length=100, verbose_name='Chức vụ')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_user', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản Django')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='LibraryApp.usergroup', verbose_name='Nhóm người dùng')),
            ],
            options={
                'verbose_name': 'Thủ thư',
                'verbose_name_plural': 'Thủ thư',
                'db_table': 'library_user',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='BookImportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('unit_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá')),
                ('amount', models.IntegerField(default=0, verbose_name='Thành tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_details', to='LibraryApp.book', verbose_name='Sách')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_details', to='LibraryApp.bookimportreceipt', verbose_name='Phiếu nhập')),
            ],
            options={
                'verbose_name': 'Chi tiết nhập sách',
                'verbose_name_plural': 'Chi tiết nhập sách',
                'db_table': 'book_import_detail',
                'indexes': [models.Index(fields=['receipt'], name='book_import_receipt_5fc428_idx'), models.Index(fields=['book'], name='book_import_book_id_445489_idx')],
                'unique_together': {('receipt', 'book')},
            },
        ),
        migrations.AddIndex(
            model_name='bookitem',
            index=models.Index(fields=['book'], name='book_item_book_id_a852c1_idx'),
        ),
        migrations.AddIndex(
            model_name='bookitem',
            index=models.Index(fields=['is_borrowed'], name='book_item_is_borr_3d69ba_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['book_title'], name='book_book_ti_497c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publish_year'], name='book_publish_f0360e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publisher'], name='book_publish_b3f21e_idx'),
        ),
        migrations.AddIndex(
            model_name='authordetail',
            index=models.Index(fields=['author'], name='author_deta_author__fd9a60_idx'),
        ),
        migrations.AddIndex(
            model_name='authordetail',
            index=models.Index(fields=['book_title'], name='author_deta_book_ti_cdf6f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='authordetail',
            unique_together={('author', 'book_title')},
        ),
        migrations.AddIndex(
            model_name='booktitle',
            index=models.Index(fields=['category'], name='book_title_categor_3991a3_idx'),
        ),
        migrations.AddIndex(
            model_name='latereturnreport',
            index=models.Index(fields=['-date'], name='late_return_date_590e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='latereturnreport',
            index=models.Index(fields=['book_item'], name='late_return_book_it_11cc86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='latereturnreport',
            unique_together={('date', 'book_item')},
        ),
        migrations.AddIndex(
            model_name='borrowreturnreceipt',
            index=models.Index(fields=['reader'], name='borrow_retu_reader__58ffd4_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowreturnreceipt',
            index=models.Index(fields=['book_item'], name='borrow_retu_book_it_75d7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowreturnreceipt',
            index=models.Index(fields=['-borrow_date'], name='borrow_retu_borrow__0d7b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowreturnreceipt',
            index=models.Index(fields=['return_date'], name='borrow_retu_return__759c92_idx'),
        ),
        migrations.AddIndex(
            model_name='reader',
            index=models.Index(fields=['email'], name='reader_email_454afe_idx'),
        ),
        migrations.AddIndex(
            model_name='reader',
            index=models.Index(fields=['reader_type'], name='reader_reader__d10796_idx'),
        ),
        migrations.AddIndex(
            model_name='reader',
            index=models.Index(fields=['is_active'], name='reader_is_acti_a674ab_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['reader'], name='receipt_reader__9b7688_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['-created_date'], name='receipt_created_cbacb5_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowreportdetailbycategory',
            index=models.Index(fields=['report'], name='borrow_repo_report__eb78ce_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowreportdetailbycategory',
            index=models.Index(fields=['book_title'], name='borrow_repo_book_ti_1cf074_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='borrowreportdetailbycategory',
            unique_together={('report', 'book_title')},
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['user_group'], name='permission_user_gr_1d645d_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['function'], name='permission_functio_a5a279_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('user_group', 'function')},
        ),
        migrations.AddIndex(
            model_name='libraryuser',
            index=models.Index(fields=['user_group'], name='library_use_user_gr_7ae6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryuser',
            index=models.Index(fields=['is_active'], name='library_use_is_acti_34f3a7_idx'),
        ),
    ]
