# Generated by Django 5.2.6 on 2025-10-19 12:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_age', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Độ tuổi thấp nhất')),
                ('min_age', models.PositiveSmallIntegerField(default=55, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Độ tuổi cao nhất')),
                ('card_validity_period', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thời hạn thẻ (tháng)')),
                ('book_return_period', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nhận sách xuất bản trong vòng (năm)')),
                ('max_borrowed_books', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số sách tối đa được mượn')),
                ('max_borrow_days', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số ngày mượn sách tối đa')),
                ('fine_rate', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá tiền phạt (VNĐ/ngày)')),
                ('enable_receipt_amount_validation', models.BooleanField(default=True, verbose_name='Kiểm tra số tiền thu không vượt quá nợ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tham số hệ thống',
                'verbose_name_plural': 'Tham số hệ thống',
                'db_table': 'parameter',
            },
        ),
        migrations.CreateModel(
            name='ReaderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_type_name', models.CharField(max_length=100, unique=True, verbose_name='Tên loại độc giả')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Loại độc giả',
                'verbose_name_plural': 'Loại độc giả',
                'db_table': 'reader_type',
                'ordering': ['reader_type_name'],
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_name', models.CharField(max_length=255, verbose_name='Tên độc giả')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('card_creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày lập thẻ')),
                ('expiration_date', models.DateTimeField(verbose_name='Ngày hết hạn thẻ')),
                ('total_debt', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng nợ (VNĐ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reader_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readers', to='LibraryApp.readertype', verbose_name='Loại độc giả')),
            ],
            options={
                'verbose_name': 'Độc giả',
                'verbose_name_plural': 'Độc giả',
                'db_table': 'reader',
                'ordering': ['-card_creation_date'],
                'indexes': [models.Index(fields=['email'], name='reader_email_454afe_idx'), models.Index(fields=['reader_type'], name='reader_reader__d10796_idx'), models.Index(fields=['is_active'], name='reader_is_acti_a674ab_idx')],
            },
        ),
    ]
