# Generated by Django 5.2.6 on 2025-10-19 12:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_parameter_readertype_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255, verbose_name='Tên tác giả')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Tiểu sử')),
            ],
            options={
                'verbose_name': 'Tác giả',
                'verbose_name_plural': 'Tác giả',
                'db_table': 'author',
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='Tên thể loại')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Thể loại',
                'verbose_name_plural': 'Thể loại',
                'db_table': 'category',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.author', verbose_name='Tác giả')),
            ],
            options={
                'verbose_name': 'Chi tiết tác giả',
                'verbose_name_plural': 'Chi tiết tác giả',
                'db_table': 'author_detail',
            },
        ),
        migrations.CreateModel(
            name='BookTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=500, verbose_name='Tên tựa sách')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='book_titles', through='LibraryApp.AuthorDetail', to='LibraryApp.author', verbose_name='Tác giả')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_titles', to='LibraryApp.category', verbose_name='Thể loại')),
            ],
            options={
                'verbose_name': 'Tựa sách',
                'verbose_name_plural': 'Tựa sách',
                'db_table': 'book_title',
                'ordering': ['book_title'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('unit_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá (VNĐ)')),
                ('publish_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Năm xuất bản')),
                ('publisher', models.CharField(max_length=255, verbose_name='Nhà xuất bản')),
                ('remaining_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng còn lại')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('edition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phiên bản')),
                ('language', models.CharField(default='Tiếng Việt', max_length=50, verbose_name='Ngôn ngữ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='LibraryApp.booktitle', verbose_name='Tựa sách')),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
                'db_table': 'book',
                'ordering': ['-publish_year', 'book_title'],
            },
        ),
        migrations.AddField(
            model_name='authordetail',
            name='book_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.booktitle', verbose_name='Tựa sách'),
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_borrowed', models.BooleanField(default=False, verbose_name='Đang được mượn')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã vạch')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_items', to='LibraryApp.book', verbose_name='Sách')),
            ],
            options={
                'verbose_name': 'Cuốn sách',
                'verbose_name_plural': 'Các cuốn sách',
                'db_table': 'book_item',
                'ordering': ['book', 'id'],
                'indexes': [models.Index(fields=['book'], name='book_item_book_id_a852c1_idx'), models.Index(fields=['is_borrowed'], name='book_item_is_borr_3d69ba_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['book_title'], name='book_book_ti_497c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publish_year'], name='book_publish_f0360e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publisher'], name='book_publish_b3f21e_idx'),
        ),
        migrations.AddIndex(
            model_name='authordetail',
            index=models.Index(fields=['author'], name='author_deta_author__fd9a60_idx'),
        ),
        migrations.AddIndex(
            model_name='authordetail',
            index=models.Index(fields=['book_title'], name='author_deta_book_ti_cdf6f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='authordetail',
            unique_together={('author', 'book_title')},
        ),
        migrations.AddIndex(
            model_name='booktitle',
            index=models.Index(fields=['category'], name='book_title_categor_3991a3_idx'),
        ),
    ]
