# Generated by Django 5.2.6 on 2025-10-19 12:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0003_author_category_authordetail_booktitle_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Tổng tiền nhập sách')),
                ('import_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập sách')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Người lập phiếu')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Phiếu nhập sách',
                'verbose_name_plural': 'Phiếu nhập sách',
                'db_table': 'book_import_receipt',
                'ordering': ['-import_date'],
                'indexes': [models.Index(fields=['-import_date'], name='book_import_import__a340f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportDetailByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Tháng')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Năm')),
                ('total_borrow_count', models.IntegerField(default=0, verbose_name='Tổng số lượt mượn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Báo cáo mượn sách theo thể loại',
                'verbose_name_plural': 'Báo cáo mượn sách theo thể loại',
                'db_table': 'report_detail_by_category',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['month', 'year'], name='report_deta_month_374931_idx')],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BookImportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('unit_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá')),
                ('amount', models.IntegerField(default=0, verbose_name='Thành tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_details', to='LibraryApp.book', verbose_name='Sách')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_details', to='LibraryApp.bookimportreceipt', verbose_name='Phiếu nhập')),
            ],
            options={
                'verbose_name': 'Chi tiết nhập sách',
                'verbose_name_plural': 'Chi tiết nhập sách',
                'db_table': 'book_import_detail',
                'indexes': [models.Index(fields=['receipt'], name='book_import_receipt_5fc428_idx'), models.Index(fields=['book'], name='book_import_book_id_445489_idx')],
                'unique_together': {('receipt', 'book')},
            },
        ),
        migrations.CreateModel(
            name='BorrowReturnReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày mượn')),
                ('due_date', models.DateTimeField(verbose_name='Ngày phải trả')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thực trả')),
                ('fine_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiền phạt trả trễ')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_receipts', to='LibraryApp.bookitem', verbose_name='Cuốn sách')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_receipts', to='LibraryApp.reader', verbose_name='Độc giả')),
            ],
            options={
                'verbose_name': 'Phiếu mượn/trả sách',
                'verbose_name_plural': 'Phiếu mượn/trả sách',
                'db_table': 'borrow_return_receipt',
                'ordering': ['-borrow_date'],
                'indexes': [models.Index(fields=['reader'], name='borrow_retu_reader__58ffd4_idx'), models.Index(fields=['book_item'], name='borrow_retu_book_it_75d7b2_idx'), models.Index(fields=['-borrow_date'], name='borrow_retu_borrow__0d7b9f_idx'), models.Index(fields=['return_date'], name='borrow_retu_return__759c92_idx')],
            },
        ),
        migrations.CreateModel(
            name='LateReturnReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày lập báo cáo')),
                ('borrow_date', models.DateTimeField(verbose_name='Ngày mượn')),
                ('late_return_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số ngày trễ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='late_reports', to='LibraryApp.bookitem', verbose_name='Cuốn sách')),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='late_reports', to='LibraryApp.reader', verbose_name='Độc giả')),
            ],
            options={
                'verbose_name': 'Báo cáo trả trễ',
                'verbose_name_plural': 'Báo cáo trả trễ',
                'db_table': 'late_return_report',
                'ordering': ['-date', '-late_return_days'],
                'indexes': [models.Index(fields=['-date'], name='late_return_date_590e8d_idx'), models.Index(fields=['book_item'], name='late_return_book_it_11cc86_idx')],
                'unique_together': {('date', 'book_item')},
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền thu')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày lập phiếu')),
                ('payment_method', models.CharField(default='Tiền mặt', max_length=50, verbose_name='Phương thức thanh toán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='LibraryApp.reader', verbose_name='Độc giả')),
            ],
            options={
                'verbose_name': 'Phiếu thu',
                'verbose_name_plural': 'Phiếu thu',
                'db_table': 'receipt',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['reader'], name='receipt_reader__9b7688_idx'), models.Index(fields=['-created_date'], name='receipt_created_cbacb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='BorrowReportDetailByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_count', models.IntegerField(default=0, verbose_name='Số lượt mượn')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tỉ lệ (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_reports', to='LibraryApp.booktitle', verbose_name='Tựa sách')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_details', to='LibraryApp.reportdetailbycategory', verbose_name='Báo cáo')),
            ],
            options={
                'verbose_name': 'Chi tiết báo cáo theo thể loại',
                'verbose_name_plural': 'Chi tiết báo cáo theo thể loại',
                'db_table': 'borrow_report_detail_by_category',
                'indexes': [models.Index(fields=['report'], name='borrow_repo_report__eb78ce_idx'), models.Index(fields=['book_title'], name='borrow_repo_book_ti_1cf074_idx')],
                'unique_together': {('report', 'book_title')},
            },
        ),
    ]
